### ISSUE TITLE
Php Symfony

### ISSUE THREAD

**Issue by AlexanderRage** [sensorario/youtube#52]
Salve io propongo una serie su Symfony comprensiva anche di esercizi da fare prima del prossimo episodio in modo da confrontarci sulle tematiche trattate ed esercitarci a casa.

**Comment by sensorario** [comment]
Interessantissimo argomento.

**Comment by sensorario** [comment]
Potrebbe andare, secondo te, un video a settimana, dove si affronta un argomento e ci si lascia con un esercizio per prepararsi all'argomento successivo? Ho un canale telegram, .. potrebbe essere il luogo giusto per un confronto? Oppure meglio questi i commenti o quelli sotto al video?

**Comment by AlexanderRage** [comment]
Per i video sarebbe molto bello fare argomento ed esercizi da dover fare a casa che poi mostrerai in un seguente video. Per i commenti i lascerei sempre sia qui che telegram, qui per lasciar traccia dei commenti e confrontarsi meglio telegram più per una chat istantanea e consigli veloci

**Comment by sensorario** [comment]
Ecco il primo video! https://youtu.be/Wc1ZCPxsPsA
