### ISSUE TITLE
CRUD: React, Bootstrap, Fastify e MongoDB

### ISSUE THREAD

**Issue by pietrodev07** [sensorario/youtube#53]

**Comment by sensorario** [comment]
@pietrodev07 ho chiuso le altre issue e vorrei stare su quelle che non nascono da me. Vorrei realizzare un-applicazione simile a Yahtzee o anche Yahtzee stesso ma con Fastify. Che ne pensi. Ci sono altre tipologie di app che ti vengono ini mente che si potrebbero implementare?
